export default {
    getUserVerifyCode: '/user/login-code',
    getRegisterCode: '/user/register-code',
    getCommonVerifyCode: '/common/send-code',
    loginByPassword: '/user/login-by-password',
    loginByVerifyCode: '/user/login-by-code',
    registerAccount: '/user/register',
    getSessionKeyByCode: '/applet/get-session',
    decryptData: '/applet/decrypt-data',
    syncWxUser: '/applet/sync-user',
    getUserData: '/user/get',
    updateUser: '/user/update',

    getTestData: '/test/test',
    getCityList: '/index/city-list',
    getAreaList: '/area/list',
    getHomeApplet: '/applet/home',
    getCommonLocation: '/common/get-location',

    getHouseList: '/house/list',
    getHouseMap: '/house/area-house',
    getHouseSearchHot: '/house/hot-search',
    getHouseById: '/house/get',
    getHouseAttr: '/house/attr',
    getHouseGroup: '/house/group',
    getSubway: '/subway/find-all',
    getAreaCircle: '/area/circle',
    getHouseAlbum: '/house/all-image',
    getHouseSand: '/house/get-sand',
    getHouseSandRoom: '/house/find-sand-room',
    getHouseAsk: '/house/ask-list',
    postHouseAsk: '/house/ask',
    getHouseComment: '/house/comment-list',
    likeHouseComment: '/house/like-comment',
    postHouseComment: '/house/comment',
    getHouseTypeList: '/house/room-list',
    getHouseTypeDetail: '/house/room-detail',
    getHouseConsultantList: '/house/consultant-list',
    postHouseCustomer: '/house/customer',
    getHouseConsultantData: '/fang-house-consultant/get',
    applyHouseConsultant: '/fang-house-consultant/apply-consultant',
    updateHouseConsultant: '/fang-house-consultant/update',
    getHouseDynamic: '/fang-house-circle/find',
    postUserDynamic: '/fang-house-circle/create',
    deleteUserDynamic: '/fang-house-circle/delete',
    getUserDynamic: '/fang-house-circle/find-self',

    getEsfList: '/esf/list',
    getEsfById: '/esf/get',
    getEsfSelfById: '/esf/get-self', //修改出售获取房源
    getEsfSaleList: '/esf/user-sale-list',
    esfSale: '/esf/sale',
    esfDelete: '/esf/delete',
    esfUpdate: '/esf/update',

    getRentList: '/rent/list',
    getRentById: '/rent/get',
    getRentSelfById: '/rent/get-self',
    getRentSaleList: '/rent/user-rent-list',
    rentAdd: '/rent/add',
    rentDelete: '/rent/delete',
    rentUpdate: '/rent/update',

    getCommunityList: '/community/list',
    getCommunityById: '/community/get',
    searchCommunity: '/community/find-by-title',

    getNewsById: '/news/get',
    getNewsList: '/news/list',
    getNewsCateList: '/news/cate-list',

    getChatDialog: '/chat/dialog',
    updateChatRead: '/chat/read',
    postChatSend: '/chat/send',
    getUnread: '/chat/get-to-read',
    getChatData: '/chat/chat-data',
    getChatUser: '/chat/scan-chat',

    getMemberUpgrade: '/member/upgrade',
    getPayment: '/pay/get',

    userCollectAdd: '/user-collection/create',
    userCollectDelete: '/user-collection/delete',
    userIsCollect: '/user-collection/is-collection',
    getCollectList: '/user-collection/find',

}